

THORSANVIL_ROOT			= $(realpath ../)

TARGET					= Parser.slib
FILE_WARNING_FLAGSXX		+= -Wno-overloaded-virtual

include ${THORSANVIL_ROOT}/build/tools/Makefile
CXXFLAGSXX				+= -Wno-deprecated-register


