

THORSANVIL_ROOT			= $(realpath ../)
LINK_LIBS				= Json Parser
TARGET					= Serialize.slib
UNITTEST_LINK_LIBS		= Json Parser
FILE_WARNING_FLAGS		+= -Wno-overloaded-virtual

JsonSerilizeVardacTest_CXXFLAGS	+= -pedantic -Werror

include ${THORSANVIL_ROOT}/build/tools/Makefile


